# Generated by Django 2.1.2 on 2018-12-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaEnfermeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('A', 'Alta'), ('B', 'Media'), ('C', 'Baja')], max_length=1)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.Clinica')),
                ('expediente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente')),
            ],
        ),
    ]
