# Generated by Django 2.1.3 on 2018-11-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0003_auto_20181014_0437'),
        ('expediente', '0002_auto_20181127_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaEnfermeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=1)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicas.Clinica')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente')),
            ],
        ),
    ]
