# Generated by Django 2.1.3 on 2018-11-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaenfermeria',
            name='clinica',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.Clinica'),
        ),
        migrations.AlterField(
            model_name='colaenfermeria',
            name='expediente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente'),
        ),
    ]
