# Generated by Django 2.1.2 on 2018-12-02 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
        ('clinicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('A', 'Alta'), ('B', 'Media'), ('C', 'Baja')], max_length=1)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.Clinica')),
                ('expediente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
