# Generated by Django 2.1.2 on 2018-12-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_auto_20181127_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaenfermeria',
            name='prioridad',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], max_length=1),
        ),
    ]
