# Generated by Django 2.1.2 on 2018-12-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_auto_20181203_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='expediente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente'),
        ),
    ]
