# Generated by Django 2.1.2 on 2018-12-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenHeces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('mucus', models.CharField(blank=True, max_length=50, null=True)),
                ('leucocitos', models.IntegerField(blank=True, null=True)),
                ('hematies', models.IntegerField(blank=True, null=True)),
                ('consistencia', models.CharField(blank=True, max_length=50, null=True)),
                ('res_alimen_macros', models.CharField(blank=True, max_length=50, null=True)),
                ('res_alimen_micros', models.CharField(blank=True, max_length=50, null=True)),
                ('levaduras', models.CharField(blank=True, max_length=50, null=True)),
                ('protozoarios', models.CharField(blank=True, choices=[('Q', 'Quistes'), ('A', 'Activos')], max_length=1, null=True)),
                ('metazoarios', models.CharField(blank=True, choices=[('Q', 'Quistes'), ('A', 'Activos')], max_length=1, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenOrina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspecto', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('ph', models.IntegerField(blank=True, null=True)),
                ('densidad', models.IntegerField(blank=True, null=True)),
                ('esteraza_leucocitaria', models.IntegerField(blank=True, null=True)),
                ('nitritos', models.IntegerField(blank=True, null=True)),
                ('proteinas', models.IntegerField(blank=True, null=True)),
                ('glucosa', models.IntegerField(blank=True, null=True)),
                ('cuerpos_cetonicos', models.IntegerField(blank=True, null=True)),
                ('urobilinogeno', models.IntegerField(blank=True, null=True)),
                ('bilirrubina', models.IntegerField(blank=True, null=True)),
                ('sangre_oculta', models.IntegerField(blank=True, null=True)),
                ('leucocitos', models.IntegerField(blank=True, null=True)),
                ('hematies', models.IntegerField(blank=True, null=True)),
                ('cilindros', models.CharField(blank=True, max_length=100, null=True)),
                ('cristales', models.CharField(blank=True, max_length=100, null=True)),
                ('parasitos', models.CharField(blank=True, max_length=100, null=True)),
                ('otros', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenSangre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbc', models.IntegerField(blank=True, null=True)),
                ('hemoglobina', models.IntegerField(blank=True, null=True)),
                ('hematocrito', models.IntegerField(blank=True, null=True)),
                ('mvc', models.IntegerField(blank=True, null=True)),
                ('mch', models.IntegerField(blank=True, null=True)),
                ('mchc', models.IntegerField(blank=True, null=True)),
                ('plaquetas', models.IntegerField(blank=True, null=True)),
                ('mpv', models.IntegerField(blank=True, null=True)),
                ('pdw', models.IntegerField(blank=True, null=True)),
                ('leucocitos', models.IntegerField(blank=True, null=True)),
                ('neutrofilos', models.IntegerField(blank=True, null=True)),
                ('linfocitos', models.IntegerField(blank=True, null=True)),
                ('monocitos', models.IntegerField(blank=True, null=True)),
                ('eosinofilos', models.IntegerField(blank=True, null=True)),
                ('basofilos', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente')),
            ],
        ),
    ]
