# Generated by Django 2.1.2 on 2018-11-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenSangre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50)),
                ('hemoglobina', models.IntegerField(blank=True, null=True)),
                ('hematocrito', models.IntegerField(blank=True, null=True)),
                ('mvc', models.IntegerField(blank=True, null=True)),
                ('mch', models.IntegerField(blank=True, null=True)),
                ('mchc', models.IntegerField(blank=True, null=True)),
                ('plaquetas', models.IntegerField(blank=True, null=True)),
                ('mpv', models.IntegerField(blank=True, null=True)),
                ('pdw', models.IntegerField(blank=True, null=True)),
                ('leucocitos', models.IntegerField(blank=True, null=True)),
                ('neutrofilos', models.IntegerField(blank=True, null=True)),
                ('linfocitos', models.IntegerField(blank=True, null=True)),
                ('monocitos', models.IntegerField(blank=True, null=True)),
                ('eucinofilos', models.IntegerField(blank=True, null=True)),
                ('basofilos', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
