# Generated by Django 2.1.3 on 2018-11-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_examenorina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenHeces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('mucus', models.CharField(blank=True, max_length=50, null=True)),
                ('leucocitos', models.CharField(blank=True, max_length=50, null=True)),
                ('hematies', models.CharField(blank=True, max_length=50, null=True)),
                ('consistencia', models.CharField(blank=True, max_length=50, null=True)),
                ('res_alimen_macros', models.CharField(blank=True, max_length=50, null=True)),
                ('res_alimen_micros', models.CharField(blank=True, max_length=50, null=True)),
                ('levaduras', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
