# Generated by Django 2.1.2 on 2018-10-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0002_auto_20181011_0341'),
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=400)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pais.Departamento')),
                ('departamentos', models.ManyToManyField(blank=True, to='clinicas.Departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pais.Municipio')),
            ],
        ),
    ]
