# Generated by Django 2.1.2 on 2018-10-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='direccion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
