# Generated by Django 2.1.2 on 2018-12-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('DUI', models.CharField(blank=True, max_length=10, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=250, null=True)),
                ('padre', models.CharField(blank=True, max_length=200, null=True)),
                ('madre', models.CharField(blank=True, max_length=200, null=True)),
                ('conyugue', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('C', 'Casado/a'), ('D', 'Divorciado/a'), ('S', 'Soltero/a'), ('V', 'Viudo/a')], max_length=1, null=True)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pais.Departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pais.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('presion_arterial', models.CharField(blank=True, max_length=7, null=True)),
                ('pulso_cardiaco', models.IntegerField(blank=True, null=True)),
                ('expediente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente')),
            ],
        ),
    ]
