# Generated by Django 2.1.3 on 2018-11-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0002_auto_20181011_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('DUI', models.IntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=250, null=True)),
                ('padre', models.CharField(blank=True, max_length=50, null=True)),
                ('madre', models.CharField(blank=True, max_length=50, null=True)),
                ('conyugue', models.CharField(blank=True, max_length=500, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pais.Departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pais.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('presion_arterial', models.CharField(blank=True, max_length=7, null=True)),
                ('pulso_cardiaco', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
