# Generated by Django 2.1.3 on 2018-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='DUI',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
