# Generated by Django 2.1.2 on 2018-12-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_auto_20181014_0437'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicas.Clinica'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamentos',
            field=models.ManyToManyField(blank=True, to='clinicas.Departamento'),
        ),
    ]
