# Generated by Django 2.1.2 on 2018-10-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='departamento_id',
            new_name='departamento',
        ),
    ]
